SELECT 
    A.CAR_ID, 
    A.CAR_TYPE, 
    ROUND(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100, 0) AS FEE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
INNER JOIN
    CAR_RENTAL_COMPANY_CAR AS A
ON
    A.CAR_ID = B.CAR_ID
INNER JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON
    A.CAR_TYPE = C.CAR_TYPE
WHERE
    (B.START_DATE < '2022-12-01' AND B.END_DATE > '2022-11-01')
AND
    (C.DURATION_TYPE = '30일 이상')
GROUP BY
    B.CAR_ID
HAVING
    (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
AND
    (FEE >= 500000 AND FEE < 2000000)
ORDER BY
    FEE DESC, CAR_TYPE, CAR_ID DESC
    